;;; Evil-Tools -- Summary:
;;; Commentary:
;;; evil and god mode configuration for Emacs
;;; generated by Zach Maas

;;; Code:

;; Configure evil mode and its packages - VIM like performance
(use-package evil
	:ensure t
	:init
	;; anzu tells us how many matches we have in the bar
	(use-package anzu
		:ensure t
		:diminish anzu-mode
		:config
		(global-anzu-mode 1))
	;; compatibility with evil mode for anzu
	(use-package evil-anzu
		:ensure t)
	;; lets use use avy with evil for jumping around easily
	(use-package evil-escape
		:ensure t
		:diminish evil-escape-mode
		:config
		(add-hook 'after-init-hook #'evil-escape-mode)
		(setq-default evil-escape-key-sequence "jk"))
	;; improved code folding - like vim
	(use-package vimish-fold
		:ensure t
		:diminish vimish-fold-mode
		:init
		;; evil compatibility for vimish-fold
		(use-package evil-vimish-fold
			:ensure t
			:config
			(evil-vimish-fold-mode t))
		:config
		(vimish-fold-global-mode t))
	(use-package evil-goggles
		:ensure t
		:diminish	evil-goggles-mode
		:config
		(evil-goggles-mode))
	(use-package evil-snipe
		:ensure t
		:diminish evil-snipe-mode
		:diminish evil-snipe-override-mode
		:diminish evil-snipe-local-mode
		:config
		(evil-snipe-override-mode 1))
	(setq evil-snipe-scope 'visible)
	(use-package evil-nerd-commenter
		:ensure t
		:config
		(evilnc-default-hotkeys))
	:config
	(evil-mode 1))

;; Evil-lispy, much better lisp editing tools
(use-package evil-lispy
	:ensure t
	:diminish evil-lispy-mode
	:init
	(use-package lispy
		:ensure t)
	:config
	(add-hook 'lisp-mode-hook #'evil-lispy-mode)
	(add-hook 'scheme-mode-hook #'evil-lispy-mode)
	(add-hook 'emacs-lisp-mode-hook #'evil-lispy-mode)
	(add-hook 'clojure-mode-hook #'evil-lispy-mode))

;; Need to learn how to use this better -- it is really useful.
( use-package evil-multiedit
	:ensure t)

;;; zm-evil.el ends here
