;;; Org-Tools -- Summary:
;;; Commentary:
;;; Org-mode configuration for Emacs
;;; generated by Zach Maas

;;; Code:

(use-package evil-org
	:ensure t)

(use-package org-bullets
	:ensure t
	:config
	(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1))))

;;; zm-org-tools.el ends here
