;;; Appearance-Configuration -- Summary:
;;; Commentary:
;;; configuration of appearance packages for Emacs
;;; generated by Zach Maas

;;; Code:

;; Configure visual line mode for text modes, wrap at fill column
(use-package visual-fill-column
	:ensure t
	:diminish visual-fill-column-mode
	:config
	(add-hook 'text-mode-hook #'visual-line-mode)
	(add-hook 'visual-line-mode-hook #'visual-fill-column-mode))

(use-package pretty-mode
	:disabled t
	:ensure t
	:config
	(global-pretty-mode t)
	(pretty-deactivate-groups
	 '(:logic :sets))
	(pretty-activate-groups
	 '(:equality :ordering :ordering-double :ordering-triple
							 :arrows :arrows-twoheaded :punctuation
							 :sub-and-superscripts :greek :arithmetic-nary)))

;; Focus for automatic code narrowing
(use-package focus
	:ensure t
	:defer t)

;; olivetti is a tool for focused writing
(use-package olivetti
	:ensure t
	:defer t)

;; Smooth scrolling. We don't enable this by default
(use-package smooth-scrolling
	:ensure t
	:defer t)

;; rainbow-mode, for hex codes
(use-package rainbow-mode
	:ensure t
	:diminish rainbow-mode
	:config
	(add-hook 'after-init-hook #'rainbow-mode))

;;; zm-appearance.el ends here
