;; init.el --- Summary
;; Commentary:
;;      ___           ___           ___
;;     /\  \         /\  \         /\  \
;;    /::\  \        \:\  \       /::\  \
;;   /:/\:\  \        \:\  \     /:/\:\  \
;;  /:/  \:\  \   _____\:\  \   /:/  \:\  \
;; /:/__/ \:\__\ /::::::::\__\ /:/__/ \:\__\
;; \:\  \ /:/  / \:\~~\~~\/__/ \:\  \ /:/  /
;;  \:\  /:/  /   \:\  \        \:\  /:/  /
;;   \:\/:/  /     \:\  \        \:\/:/  /
;;    \::/  /       \:\__\        \::/  /
;;     \/__/         \/__/         \/__/
;;                  EMACS
;;
;; Emacs configuration file - generated by Zach Maas for Emacs 25.2
;; Configured for use on Arch Linux, vc using git
;; For more information, see README

;;; Code:

;; Allow packages to load
(package-initialize)

;; Setup Garbage Collection Threshold for Speed
(setq gc-cons-threshold (* 50 1024 1024))

;; Load bootstrapping code
(load-file "~/.emacs.d/core/jack-in.el")

;; Load from personal init files
(ono! :secrets "personal")

;; Load startup defults to save our sanity
(ono! :startup "archives")
(ono! :startup "defaults")

;; Leverage our bootstrapping code
(ono! :core "evil")
(ono! :core "ivy")
(ono! :core "hydras")
(ono! :core "completions")
(ono! :core "error-checks")
(ono! :core "style-checks")
(ono! :core "utils")
(ono! :core "shell")

;; Load various app configurations
(ono! :apps "mail")
(ono! :apps "irc")

;; Theming configuration files
(ono! :core "themes")
(ono! :core "appearance")

;; Load language specific configurations
;; Markup Langauges
(ono! :lang "latex")
(ono! :lang "org")
(ono! :lang "md")
;; Programming Languages
(ono! :lang "lisp")
(ono! :lang "clojure")
(ono! :lang "python")
(ono! :lang "haskell")
(ono! :lang "go")
(ono! :lang "r")
(ono! :lang "c++")

;; Set our default theme
(daytime-space-theme)

;; Load custom-set-variables file
(setq custom-file "~/.emacs.d/emacs-custom.el")
(load custom-file)

(provide 'init)

;;; init.el ends here
