Emacs for your Ono-Sendai Cyberspace 7.

This repository contains the full contents of my day-to-day emacs configuration. Inspired by vim, spacemacs, and cyberpunk. It attempts to provide an ergonomic and modern development and writing environment with consistent behavior. Targeting *Arch Linux* on kernel 4.10+, emacs version *25+*. It is always a work in progress and currently undergoing major improvements and refactoring.

* Languages
The primary languages I work on using emacs are:
- Python for shell scripting
- Golang for the quick and easy, slowly supplanting python
- Clojure for long running programs and CLJS
- LaTeX for all of my homework and report writing
- Orgmode for task management and remembering things
	
* TODO:
** Shackle for managing popup buffers
- Steal this macro from DOOM
** DONE Improved session and workgroup management
- In-progress - Preliminary work for persp-mode is done
- Need to remove all references to eyebrowse
** DONE Pretty re-theme using nerdfonts
** DONE vim binds for ripgrep
I actually need to do this for all sorts of commands.
** DONE eval-buffer evil bind
** Improved modeline
- More work on Spaceline
** DONE Comms
*** DONE IRC
*** DONE Email
** Improved custom elisp for loading modes and files
	 This will require a major refactor of the project, but is ultimately necessary. This repo is getting pretty big and a more efficent method for loading and providing individual modules will significantly improve the extensibility and managment of the repo.
** All of the orgmode setup
