;;; C++-Tools -- Summary:
;;; Commentary:
;;; configuration of C++ editing packages for Emacs
;;; generated by Zach Maas

;;; Code:

;; Add Irony
(use-package irony
	:ensure t
	:config
	(add-hook 'c++-mode-hook 'irony-mode)
	(add-hook 'irony-mode-hook 'irony-cdb-autosetup-compile-options))
)
;; special per-mode keybindings for C++
(general-define-key
 :states '(normal visual insert emacs)
 :keymaps 'c++-mode-map
 :prefix "SPC"
 :non-normal-prefix "M-SPC"
 "l" '(:ignore t :which-key "layer")
 "lr" '(cider-repl :which-key "cider repl")
 "li" '(cider-jack-in :which-key "jack in")
 "lI" '(cider-jack-in-clojurescript :which-key "jack in cljs")
 "ll" '(cider-eval-defun-at-point :which-key "eval def")
 "lc" '(cider-eval-buffer :which-key "eval buffer"))

;; c++-tools.el ends here
