;;; Go-Tools -- Summary:
;;; Commentary:
;; configuration of golang editing packages for Emacs
;;; generated by Zach Maas

;;; Code:

(use-package go-mode
	:ensure t)

(use-package company-go
	:ensure t)

(defun go-mode-setup-hook ()
	; Add company backend
  (lambda ()
    (set (make-local-variable 'company-backends) '(company-go)))
	; Custom compile command
  (setq compile-command "go build -v && go test -v && go vet")
	; Automatically control imports
  (setq gofmt-command "goimports")
	; Call Gofmt before saving
	(add-hook 'before-save-hook 'gofmt-before-save))

(add-hook 'go-mode-hook 'go-mode-setup-hook)


(general-define-key
	 :states '(normal visual insert emacs)
	 :keymaps 'go-mode-map
	 :prefix "SPC"
	 :non-normal-prefix "M-SPC"
		"l" '(:ignore t :which-key "layer")
		"ll" '(go-golint :which-key "lint")
		"ld" '(godef-jump :which-key "goto def")
		"lD" '(pop-tag-mark :which-key "pop-back")
		"lc" '(compile :which-key "compile"))


;;; zm-lisp-tools.el ends here
