;;; Lisp-Tools -- Summary:
;;; Commentary:
;; configuration of common Lisp editing packages for Emacs
;;; generated by Zach Maas

;;; Code:

;; Require common lisp
(use-package cl
	:ensure t
	:defer t)

;; LISP Development Setup
;; Uses SLIME configured for sbcl
(use-package slime
	:ensure t
	:defer t
	:init
	;;(use-package slime-company
	;;	:ensure t)
	:config
	(setq inferior-lisp-program "sbcl")
	(setq slime-contribs '(slime-fancy))
	(slime-setup '(slime-company)))

(defun my/slime-mode-hook ()
  (add-to-list 'company-backends 'company-slime))
(add-hook 'slime-mode-hook 'my/slime-mode-hook)

;; Setup for racket for SICP
(use-package geiser
	:ensure t
	:config
	(add-hook 'scheme-mode-hook #'geiser-mode))

;; special per-mode keybindings for racket Editing
(general-define-key
	 :states '(normal visual insert emacs)
   :keymaps 'geiser-mode-map
	 :prefix "SPC"
	 :non-normal-prefix "M-SPC"
	  "l" '(:ignore t :which-key "layer")
		"lr" '(run-racket :which-key "racket repl")
		"ll" '(geiser-eval-definition :which-key "eval def")
		"lc" '(geiser-eval-buffer :which-key "eval buffer")
		"lj" '(geiser-insert-lambda :which-key "lambda"))

;;; zm-lisp-tools.el ends here
