;;; Markdown-Tools -- Summary:
;;; Commentary:
;;; Markdown configuration for Emacs
;;; generated by Zach Maas

;; This file contains config for all different markdown modes,
;; orgmode excepted
;;; Code:

(use-package markdown-mode
  :ensure t
  :commands (markdown-mode gfm-mode)
  :mode (("README\\.md\\'" . gfm-mode)
         ("\\.md\\'" . markdown-mode)
         ("\\.markdown\\'" . markdown-mode))
  :init (setq markdown-command "multimarkdown"))

(use-package yaml-mode
	:ensure t)

;; FIXME
(general-define-key
 :states '(normal visual insert emacs)
 :prefix "SPC"
 :non-normal-prefix "M-SPC"
 "l" '(:ignore t :which-key "layer"))
; "la" '(org-agenda :which-key "agenda")
; "lc" '(org-capture :which-key "capture")
; "ls" '(org-schedule :which-key "schedule")
; "ld" '(org-deadline :which-key "deadline")
; "lr" '(org-refile :which-key "refile"))

;;; zm-org-tools.el ends here
