;;; Emacs-Defaults -- Summary:
;;; Commentary:
;;;	Load any startup generic defaults
;;; generated by Zach Maas

;;; Code:

;; Save history of everything by default
(savehist-mode t)

;; Allow us to diminish packages with use-package
(require 'diminish)

;; Set reasonable defaults for editing
(setq inhibit-startup-message t)
;; 80 columns, no UI elements  enabled
(setq-default fill-column 80)
(setq-default tab-width 2)
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)

;; Make font-lock work better in the background
(setq jit-lock-defer-time nil
      ;; jit-lock-stealth-nice 0.1
      jit-lock-stealth-time 1
      jit-lock-stealth-verbose nil)
(defalias 'yes-or-no-p 'y-or-n-p)
(setq line-move-visual t)

;; Put automatic backups in the	homme folder
(setq backup-directory-alist '(("." . "~/.emacsbackups")))

;; Setup passwords using .authinfo
(setq auth-sources
			'((:source "~/.emacs.d/secrets/.authinfo.gpg")))

;; Prevents us from fat fingering and accidentally closing emacs
(setq confirm-kill-emacs 'y-or-n-p)
