;;; Emacs-Archives -- Summary:
;;; Commentary:
;;; Tell Emacs where our package archives are located
;;; generated by Zach Maas

;;; Code:

;; Configure package archives
(setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
												 ("org" . "https://orgmode.org/elpa/")
												 ("marmalade" . "https://marmalade-repo.org/packages/")
												 ("melpa" . "https://melpa.org/packages/")))

;; Force GNUtls to use real security
(setq gnutls-min-prime-bits 4096)
(setq tls-checktrust t)

;; Use package.el
(package-initialize)
(setq package-enable-at-startup nil)

;;; Make sure we have use-package
(unless (package-installed-p 'use-package)
	(package-install 'use-package))
(require 'use-package)

;; Add use-package :quelpa command for special packages
(use-package quelpa-use-package
	:ensure t
	:init
	(use-package quelpa
		:ensure t))

;; Load auto-compile for any future editing of elisp files
(use-package auto-compile
	:ensure t
	:config
	(add-hook 'after-init-hook #'auto-compile-mode)
	(auto-compile-on-save-mode t)
	(auto-compile-on-load-mode t))

;; Always prefer newer files when loading
(setq load-prefer-newer t)

;; Paradox for better package viewing
(use-package paradox
	:ensure t
	:config
	(paradox-enable))

(defun ono-re-init ()
	"Reloads init.el after any changes that we have made."
	(interactive)
	(load user-init-file))
