;;; Error-Tools -- Summary:
;;; Commentary:
;;; configuration of error checking packages for Emacs
;;; generated by Zach Maas

;;; Code:

;; ispell - simple and easy spellchecking for LaTeX editing
(use-package ispell
	:ensure t
	:defer t
	:init
	(use-package flyspell-correct
		:ensure t
		:init
		(use-package flyspell-correct-ivy
			:ensure t)
		:config)
	:config
	(setq ispell-program-name "aspell")
	(setq ispell-dictionary "english")
	(add-hook 'prog-mode-hook 'flyspell-prog-mode)
	(add-hook 'text-mode-hook 'flyspell-mode)
	(add-hook 'text-mode-hook 'flyspell-buffer)
	(set 'flyspell-correct-auto-mode nil))

;; writegood mode checks errors
(use-package writegood-mode
	:ensure t
	:config
	(add-hook 'text-mode-hook #'writegood-mode))

;; langtool provides easy grammar checking
(use-package langtool
	:ensure t
	:config
	(setq langtool-java-classpath
      "/usr/share/languagetool:/usr/share/java/languagetool/*"))

;; flycheck gives us global syntax checking and eroor popups in our code
(use-package flycheck
	:ensure t
	:diminish (flycheck-mode "Fc")
	:defer t
	:init
	(use-package flycheck-pos-tip
		:ensure t)
	:config
	(add-hook 'after-init-hook #'global-flycheck-mode)
	(add-hook 'prog-mode-hook #'flycheck-pos-tip-mode))

;;; zm-errorchecks.el ends here
