;;; Highlighting-Configuration -- Summary:
;;; Commentary:
;;; configuration of text-highlighting packages for Emacs
;;; generated by Zach Maas

;;; Code:

;; Make all symbols pretty
(global-prettify-symbols-mode t)

;; Show trailing whitespace
(setq-default show-trailing-whitespace t)
;; Modes to hide trailing whitespace
(add-hook 'mu4e-view-mode-hook (lambda () (setq show-trailing-whitespace nil)))
(add-hook 'undo-tree-mode-hook (lambda () (setq show-trailing-whitespace nil)))

;; highlight symbols when we are over them - so pretty
(use-package highlight-thing
	:ensure t
	:diminish highlight-thing-mode
	:config
	(global-highlight-thing-mode t))

;; subtle lines to show our tab level in code
(use-package highlight-indent-guides
	:ensure t
	:diminish highlight-indent-guides-mode
	:config
	(setq highlight-indent-guides-method 'character)
	(add-hook 'prog-mode-hook 'highlight-indent-guides-mode))

;; all code identifiers get pretty colors
(use-package color-identifiers-mode
	:ensure t
	:diminish color-identifiers-mode
	:config
	(add-hook 'after-init-hook 'global-color-identifiers-mode))

;; make our delimiters rainbows! much easier to see sexps
(use-package rainbow-delimiters
	:ensure t
	:diminish rainbow-delimiters-mode
	:config
	(add-hook 'prog-mode-hook #'rainbow-delimiters-mode)
	(setq rainbow-delimiters-max-face-count 3)
	(set-face-attribute 'rainbow-delimiters-unmatched-face nil
											:foreground 'unspecified
											:inherit 'error))

;; highlights numbers, not that complicated
(use-package highlight-numbers
	:ensure t
	:diminish highlight-numbers-mode
	:config
	(add-hook 'prog-mode-hook #'highlight-numbers-mode)
	(add-hook 'prog-mode-hook #'show-paren-mode))

;; Highlight parentheses when we're hovering
(use-package highlight-parentheses
  :ensure t
  :diminish highlight-parentheses-mode
	:config
	(add-hook 'prog-mode-hook #'highlight-parentheses-mode))

;; prettyify fonts
(setq font-lock-maximum-decoration t)

;; Highlight specific keywords in prog-modes
(defun ono-add-watchwords ()
  "Highlight FIXME, TODO, and NOCOMMIT in code TODO"
  (font-lock-add-keywords
   nil '(("\\<\\(TODO\\(?:(.*)\\)?:?\\)\\>"  1 'warning prepend)
         ("\\<\\(FIXME\\(?:(.*)\\)?:?\\)\\>" 1 'error prepend)
         ("\\<\\(NOCOMMIT\\(?:(.*)\\)?:?\\)\\>"  1 'error prepend))))
(add-hook 'prog-mode-hook #'ono-add-watchwords)

;; highlighting.el ends here
