;;; Hydra-Tools -- Summary:
;;; Commentary:
;; configuration of the Hydra for Emacs
;;; generated by Zach Maas

;;; Code:

;; IN PROGRESS - Behold the Mighty Hydra! Dynamic keybinds that stick around
(use-package hydra
	:ensure t
	:defer t)

;; HYDRAS
(defhydra sp-slurpbarf ()
	"smarparens slurp barf"
	(")" sp-forward-slurp-sexp "Slurp Forward")
	("(" sp-backward-slurp-sexp "Slurp Backward")
	("9" sp-forward-barf-sexp "Barf Forward")
	("0" sp-backward-barf-sexp "Barf Backward"))

(defhydra eyebrowse-hydra ()
	"A Hydra providing config for eyebrowse evil bindings"
	("h" eyebrowse-next-window-config "Next window")
	("l" eyebrowse-prev-window-config "Previous window")
	("w" eyebrowse-last-window-config "Last window")
	("x" eyebrowse-close-window-config "Last window")
	("0" eyebrowse-switch-to-window-config-0 "Window 0")
	("1" eyebrowse-switch-to-window-config-1 "Window 1")
	("2" eyebrowse-switch-to-window-config-2 "Window 2")
	("3" eyebrowse-switch-to-window-config-3 "Window 3")
	("4" eyebrowse-switch-to-window-config-4 "Window 4"))

;;; zm-hydras.el ends here
