;;; Commentary:
;;; Emacs configuration file - generated by Zach Maas for Emacs 25.2
;;; This file defines a set of commands and macros for easily loading
;;; the rest of my configuration
;;; Heavily inspired by hlissner's configuration

;;; BEEP BEEP! (cdr UNDER CONSTRUCTION)

;;; Code:

;; Variables for making this work
;; User path files
(defvar ono-emacs-dir (expand-file-name user-emacs-directory)
  "The path to this emacs.d directory.")

(defvar ono-modules
	"A hash-table of loaded modules, to be digested by ono-init!")

;; Function to reliably fetch a module path
(defun ono-module-path (module file)
  "Get the full path to a module: e.g. :lang emacs-lisp maps to
~/.emacs.d/modules/lang/emacs-lisp/ and will append FILE if non-nil."
  (when (keywordp module)
    (setq module (substring (symbol-name module) 1)))
	(expand-file-name
	 (concat ono-emacs-dir "/" module "/" file ".el")))

;; Function to reliably fetch a submodule path
(defun ono-submodule-path (module submodule file)
  "Get the full path to a submodule: e.g. :lang emacs-lisp maps to
~/.emacs.d/modules/lang/emacs-lisp/ and will append FILE if non-nil."
  (when (keywordp module)
    (setq module (substring (symbol-name module) 1)))
  (when (keywordp submodule)
    (setq submodule (substring (symbol-name submodule) 1)))
	(expand-file-name
	 (concat ono-emacs-dir "/" module "/" submodule "/" file ".el")))

(defun ono-module-load (module file)
	"Loads a module from the path fetched using ono-module-path"
	(load (ono-module-path module file)))

(defun ono-submodule-load (module submodule file)
	"Loads a module from the path fetched using ono-module-path"
	(load (ono-submodule-path module submodule file)))

(defun ono-module! (module file)
	"Loads initialization files one at a time"
	(ono-module-load module file))

(defun ono-submodule! (module submodule file)
	"Loads initialization files one at a time"
	(ono-submodule-load module submodule file))

(defun ono! (module &optional submodule file)
	"Loads a module or a submodule"
	(if (keywordp submodule)
			(ono-submodule! module submodule file)
		(ono-module! module submodule)))

;;; jack-in.el ends here
