;;; Commentary:
;;; Emacs configuration file - generated by Zach Maas for Emacs 25.2
;;; This file defines a set of commands and macros for easily loading
;;; the rest of my configuration
;;; Heavily inspired by hlissner's configuration

;;; BEEP BEEP! (cdr UNDER CONSTRUCTION)

;;; Code:

;; Variables for making this work
;; User path files
(defvar ono-emacs-dir (expand-file-name user-emacs-directory)
  "The path to this emacs.d directory.")

(defvar ono-modules
	"A hash-table of loaded modules, to be digested by ono-init!")

;; Function to reliably fetch a module path
(defun ono-module-path (module file)
  "Get the full path to a module: e.g. :lang emacs-lisp maps to
~/.emacs.d/modules/lang/emacs-lisp/ and will append FILE if non-nil."
  (when (keywordp module)
    (setq module (substring (symbol-name module) 1)))
  (expand-file-name (concat ono-emacs-dir "/" module "/" file ".el")))

(defun ono-module-load (module file)
	"Loads a module from the path fetched using ono-module-path"
	(load-file (ono-module-path module file)))

(defun ono-load-module-list ()
	"Fills ono-modules with a provided set of modules"
	(unless ono-modules (setq ono-modules (make-hash-table)))
	(dolist (m modules)))

(defmacro ono! (module file)
	"Loads initialization files one at a time"
	(ono-module-load module file))

;;; jack-in.el ends here
