;;; Emacs-Mail -- Summary:
;;; Commentary:
;; configuration of mu4e for Emacs
;;; generated by Zach Maas

;;; Code:

;; Note: mu4e custom bindings are under the o[rg] mode leader binding.
;; See evil-tools.el for details
(require 'mu4e)
(require 'smtpmail)
(setq message-send-mail-function 'smtpmail-send-it)

(use-package evil-mu4e
	:ensure t
	:config
	(evil-set-initial-state 'mu4e-main-mode 'emacs))
(setq mu4e-maildir "~/.mail/")

;; Store account personal settings in an untracked file
(load-file "~/.emacs.d/core/mail-private.el")

;; Custom bookmarks
(add-to-list 'mu4e-bookmarks
             '("flag:unread AND date:today..now" "Todays Unread Email" ?i)
						 '("flag:unread AND date:7d..now" "This Week's Unread Email" ?o))

(defun my-mu4e-set-account ()
  "Set the account for composing a message."
  (let* ((account
          (if mu4e-compose-parent-message
              (let ((maildir (mu4e-message-field mu4e-compose-parent-message :maildir)))
                (string-match "/\\(.*?\\)/" maildir)
                (match-string 1 maildir))
            (completing-read (format "Compose with account: (%s) "
                                     (mapconcat #'(lambda (var) (car var))
                                                my-mu4e-account-alist "/"))
                             (mapcar #'(lambda (var) (car var)) my-mu4e-account-alist)
                             nil t nil nil (caar my-mu4e-account-alist))))
         (account-vars (cdr (assoc account my-mu4e-account-alist))))
    (if account-vars
        (mapc #'(lambda (var)
                  (set (car var) (cadr var)))
              account-vars)
      (error "No email account found"))))

(add-hook 'mu4e-compose-pre-hook 'my-mu4e-set-account)

(setq mu4e-sent-messages-behavior 'delete)
(setq mu4e-get-mail-command "mbsync -a")
(setq mu4e-completing-read-function 'completing-read)
(setq message-kill-buffer-on-exit t)

;; mail.el ends here
