;;; Language Server Protocol Support -- Summary:
;;; Commentary:
;;; configuration of lsp support for Emacs
;;; generated by Zach Maas

;;; Code:

(use-package lsp-mode
	:ensure t
	:init
	(use-package lsp-ui
		:ensure t
		:config
		(add-hook 'lsp-mode-hook 'lsp-ui-mode)
		(setq lsp-ui-doc-max-width 80
					lsp-ui-doc-max-height 15))
	(use-package company-lsp
		:ensure t
		:config
		(setq company-lsp-cache-candidates 'auto
					company-lsp-async t
					company-lsp-enable-recompletion t)
		(push 'company-lsp company-backends))
	:config
	(add-hook 'lsp-after-open-hook 'lsp-enable-imenu))

;;; lsp.el ends here
