;;; Emacs-Utilities -- Summary:
;;; Commentary:
;; configuration of utility packages for Emacs
;;; generated by Zach Maas

;;; Code:

(use-package vagrant
	:ensure t
	:init
	(use-package vagrant-tramp
		:ensure t))

(use-package docker
	:ensure t
	:init
	(setq docker-command "sudo docker")
	(use-package docker-tramp
		:ensure t)
	(use-package dockerfile-mode
		:ensure t
		:config
		(add-to-list 'auto-mode-alist '("Dockerfile\\'" . dockerfile-mode))))

;;; virtualization.el ends here
