;;; Emacs-Utilities -- Summary:
;;; Commentary:
;; configuration of utility packages for Emacs
;;; generated by Zach Maas

;;; Code:

(use-package vagrant
	:straight t
	:init
	(use-package vagrant-tramp
		:straight t))

(use-package docker
	:straight t
	:config
	(setq docker-command "docker"
				docker-run-as-root t)
	(use-package docker-tramp
		:straight t)
	(use-package dockerfile-mode
		:straight t
		:config
		(add-to-list 'auto-mode-alist '("Dockerfile\\'" . dockerfile-mode))))

(use-package terraform-mode
	:straight t)

(use-package salt-mode
	:straight t )

;;; virtualization.el ends here
