;;; Error-Tools -- Summary:
;;; Commentary:
;;; configuration of error checking packages for Emacs
;;; generated by Zach Maas

;;; Code:

;; ispell - simple and easy spellchecking for LaTeX editing
(use-package ispell
	:diminish	(flyspell-mode "sp")
	:diminish	(flyspell-prog-mode "sp")
	:init
	(use-package flyspell-correct
		:ensure t
		:init
		(use-package flyspell-correct-ivy
			:ensure t)
		:config)
	:config
	(setq ispell-program-name "aspell")
	(setq ispell-dictionary "english")
	(setq ispell-extra-args
				(list "--sug-mode=ultra" ;; ultra|fast|normal|bad-spellers
							"--lang=en_US"))
	(add-hook 'prog-mode-hook 'flyspell-prog-mode)
	(lambda ()
		(unless (derived-mode-p 'git-commit-mode)
			(flyspell-mode t)))
	(add-hook 'text-mode-hook 'flyspell-mode)
	(set 'flyspell-correct-auto-mode nil))

;; writegood mode checks errors
(use-package writegood-mode
	:ensure t
	:config
	(add-hook 'text-mode-hook #'writegood-mode))

;; langtool provides easy grammar checking
(use-package langtool
	:ensure t
	:config
	(setq langtool-java-classpath
				"/usr/share/languagetool:/usr/share/java/languagetool/*"))

;; Synosaurus gives us easy synonyms
(use-package synosaurus
  :ensure t
	:diminish ""
  :init
  (setq-default synosaurus-backend 'synosaurus-backend-wordnet)
	(setq-default synosaurus-choose-method 'ido)
  (add-hook 'after-init-hook #'synosaurus-mode))

;; flycheck gives us global syntax checking and eroor popups in our code
(use-package flycheck
	:ensure t
	:diminish (flycheck-mode "fc")
	:defer t
	:init
	(use-package flycheck-popup-tip
		:ensure t)
	:config
	(setq flycheck-check-syntax-automatically '(mode-enabled save
																													 idle-change new-line))
	(add-hook 'after-init-hook #'global-flycheck-mode)
	(add-hook 'prog-mode-hook #'flycheck-popup-tip-mode))

;;; zm-errorchecks.el ends here
