;;; Stylecheck-Tools -- Summary:
;;; Commentary:
;;; configuration of style checking and management packages for Emacs
;;; generated by Zach Maas

;;; Code:

;; Enforce maximum line lengths in programming modes
(use-package column-enforce-mode
  :straight t
  :diminish column-enforce-mode
  :config
  (add-hook 'prog-mode-hook 'column-enforce-mode))

;; fill-column indication
(use-package fill-column-indicator
  :straight t
  :config
  (setq whitespace-style '(face trailing)))

;; amazing plugin - gives us perfect indentation automatically for code
(use-package aggressive-indent
  :straight t
  :diminish aggressive-indent-mode
  :config
  (add-hook 'after-init-hook #'aggressive-indent-global-mode)
  (add-to-list 'aggressive-indent-excluded-modes 'haskell-mode))

;; Cleans up whitespace at newlines
(use-package clean-aindent-mode
  :straight t
  :config
	(set 'clean-aindent-is-simple-indent t)
  (define-key global-map (kbd "RET") 'newline-and-indent))

;; keeps our parentheses balanced and allows for easy manipulation
(use-package smartparens
  :straight t
  :diminish smartparens-mode
  :config
  (require 'smartparens-config)
	(add-hook 'prog-mode-hook 'turn-on-smartparens-strict-mode)
	(add-hook 'after-init-hook '(lambda () (show-smartparens-global-mode t)))
  (add-hook 'after-init-hook 'smartparens-global-mode))

;; intelligently cleanup whitespace on save
(use-package whitespace-cleanup-mode
  :straight t
  :diminish whitespace-cleanup-mode
  :config
  (add-hook 'after-init-hook 'whitespace-cleanup-mode))

;;; zm-stylechecks.el ends here
