;;; Clojure-Tools -- Summary:
;;; Commentary:
;; configuration of Clojure/script editing packages for Emacs
;;; generated by Zach Maas

;;; Code:

;; Add Cider
(use-package cider
	:ensure t
	:config
	(add-hook 'clojure-mode-hook 'cider-mode))

;; Improved	sexp evaluation
(use-package cider-eval-sexp-fu
	:ensure t)

;; special per-mode keybindings for CIDER
(general-define-key
 :states '(normal visual insert emacs)
 :keymaps 'cider-mode-map
 :prefix "SPC"
 :non-normal-prefix "M-SPC"
 "l" '(:ignore t :which-key "layer")
 "lr" '(cider-repl :which-key "cider repl")
 "li" '(cider-jack-in :which-key "jack in")
 "lI" '(cider-jack-in-clojurescript :which-key "jack in cljs")
 "ll" '(cider-eval-defun-at-point :which-key "eval def")
 "lc" '(cider-eval-buffer :which-key "eval buffer"))

;;; clojure.el ends here
