;;; Debug-Tools -- Summary:
;;; Commentary:
;;; configuration of debugging packages for Emacs
;;; generated by Zach Maas

;;; Code:

(use-package realgud
	:straight t
	:config)

;; debug.el ends here
