;;; Go-Tools -- Summary:
;;; Commentary:
;; configuration of golang editing packages for Emacs
;;; generated by Zach Maas

;;; Code:

(use-package go-mode
	:ensure t)

(use-package golint
	:ensure t)

(use-package flycheck-gometalinter
	:ensure t)

(use-package company-go
	:ensure t)

(use-package go-complete
	:ensure t)

;; (defun go-mode-setup-hook ()
;; 	"Set up go-mode"
;; 	(add-to-list 'company-backends 'company-go) ; Add company backend
;;   (setq compile-command "go build -v && go test -v && go vet") ; Custom compile command
;;   (setq gofmt-command "gofmt") ; Automatically control imports
;; 	)

;; (add-hook 'go-mode-hook 'go-mode-setup-hook)

(general-define-key
 :states '(normal visual insert emacs)
 :keymaps 'go-mode-map
 :prefix "SPC"
 :non-normal-prefix "M-SPC"
 "l" '(:ignore t :which-key "layer")
 "ll" '(golint :which-key "lint")
 "lf" '(gofmt :which-key "format")
 "lv" '(govet :which-key "vet")
 "ld" '(godef-jump :which-key "goto def")
 "lD" '(pop-tag-mark :which-key "pop-back")
 "lc" '(multi-compile-run :which-key "compile"))

;;; zm-lisp-tools.el ends here
