;;; Haskell-Tools -- Summary:
;;; Commentary:
;; configuration of haskell editing packages for Emacs
;;; generated by Zach Maas

;;; Code:

;; General haskell mode
(use-package haskell-mode
	:ensure t)

(use-package intero
	:ensure t
	:config
	(add-hook 'haskell-mode-hook 'intero-mode))

;;; haskell.el ends here
