;;; Haskell-Tools -- Summary:
;;; Commentary:
;; configuration of haskell editing packages for Emacs
;;; generated by Zach Maas

;;; Code:

;; Depndencies: hlint hoogle intero

;; General haskell mode
(use-package haskell-mode
	:straight t
	:config
	(setq haskell-font-lock-symbols t)
	(add-hook 'haskell-mode-hook (lambda () (aggressive-indent-mode nil)))
	(add-hook 'haskell-mode-hook (lambda () (pretty-mode nil))))

(use-package intero
	:straight t
	:config
	(add-hook 'after-init-hook #'intero-global-mode))

(use-package hindent
	:straight t
	:config
	(add-hook 'haskell-mode-hook #'hindent-mode))

;; special per-mode keybindings for	intero/haskell
(general-define-key
 :states '(normal visual insert emacs)
 :keymaps 'haskell-mode-map
 :prefix "SPC"
 :non-normal-prefix "M-SPC"
 "l" '(:ignore t :which-key "layer")
 "lc" '(multi-compile-run :which-key "compile")
 "lr" '(intero-repl :which-key "start repl")
 "lR" '(intero-repl-clear-buffer :which-key "clear repl")
 "ll" '(intero-repl-switch-back :which-key "switch repl")
 "ld" '(intero-goto-definition :which-key "goto def")
 "li" '(intero-ident-at-point :which-key "identify")
 "ll" '(intero-apply-suggestions :which-key "apply suggestions")
 "le" '(intero-with-repl-buffer :which-key "eval in repl"))

;;; haskell.el ends here
