;;; Java-Tools -- Summary:
;;; Commentary:
;; configuration of Java/script editing packages for Emacs
;;; generated by Zach Maas

;;; Code:

;; Auto disassembly of java bytecode
(use-package autodisass-java-bytecode
  :straight t)

;; Use the eclipse server implementation
(use-package lsp-java
	:straight t
	:config
	(add-hook 'java-mode-hook #'lsp))

;; special per-mode keybindings for java lsp
(general-define-key
 :states '(normal visual insert emacs)
 :keymaps '(java-mode-map)
 :prefix "SPC"
 :non-normal-prefix "M-SPC"
 "l" '(:ignore t :which-key "layer")
 "lr" '(lsp-restart-workspace :which-key "restart")
 "lt" '(lsp-jt-browser :which-key "tests")
 "lf" '(lsp-format-buffer :which-key "format")
 "lc" '(lsp-java-build-project :which-key "compile project")
 "lo" '(lsp-java-organize-imports :which-key "optimize"))

;;; java.el ends here
