;;; Java-Tools -- Summary:
;;; Commentary:
;; configuration of Java/script editing packages for Emacs
;;; generated by Zach Maas

;;; Code:

;; Auto disassembly of java bytecode
(use-package autodisass-java-bytecode
  :straight t)

(use-package meghanada
	:straight t
  :config
  (meghanada-install-server)
  (setq meghanada-use-company	t
				meghanada-use-flycheck t
				meghanada-use-eldoc t)
  (add-hook 'java-mode-hook
            (lambda ()
              (meghanada-mode t)
              (add-hook 'before-save-hook 'meghanada-code-beautify-before-save)))

  :config
  (use-package realgud
    :straight t)
  (setq indent-tabs-mode nil)
  (setq tab-width 2)
  (setq meghanada-server-remote-debug t)
  (setq meghanada-javac-xlint "-Xlint:all,-processing")
  :bind
  (:map meghanada-mode-map
        ("C-S-t" . meghanada-switch-testcase)
        ("M-RET" . meghanada-local-variable)
        ("C-M-." . helm-imenu)
        ("M-r" . meghanada-reference)
        ("M-t" . meghanada-typeinfo)
        ("C-z" . hydra-meghanada/body))
  :commands
  (meghanada-mode))

(use-package groovy-mode
	:straight t
	:config)


(defhydra hydra-meghanada (:hint nil :exit t)
	"
^Edit^                           ^Tast or Task^
^^^^^^-------------------------------------------------------
_f_: meghanada-compile-file      _m_: meghanada-restart
_c_: meghanada-compile-project   _t_: meghanada-run-task
_o_: meghanada-optimize-import   _j_: meghanada-run-junit-test-case
_s_: meghanada-switch-test-case  _J_: meghanada-run-junit-class
_v_: meghanada-local-variable    _R_: meghanada-run-junit-recent
_i_: meghanada-import-all        _r_: meghanada-reference
_g_: magit-status                _T_: meghanada-typeinfo
_l_: helm-ls-git-ls
_q_: exit
"
  ("f" meghanada-compile-file)
  ("m" meghanada-restart)

  ("c" meghanada-compile-project)
  ("o" meghanada-optimize-import)
  ("s" meghanada-switch-test-case)
  ("v" meghanada-local-variable)
  ("i" meghanada-import-all)

  ("g" magit-status)
  ("l" helm-ls-git-ls)

  ("t" meghanada-run-task)
  ("T" meghanada-typeinfo)
  ("j" meghanada-run-junit-test-case)
  ("J" meghanada-run-junit-class)
  ("R" meghanada-run-junit-recent)
  ("r" meghanada-reference)

  ("q" exit)
  ("z" nil "leave"))

;; special per-mode keybindings for CIDER
(general-define-key
 :states '(normal visual insert emacs)
 :keymaps '(java-mode-map)
 :prefix "SPC"
 :non-normal-prefix "M-SPC"
 "l" '(:ignore t :which-key "layer")
 "lh" '(hydra-meghanada/body :which-key "hydra")
 "lr" '(meghanada-restart :which-key "restart")
 "ll" '(meghanada-compile-file :which-key "compile file")
 "lc" '(meghanada-compile-project :which-key "compile project")
 "lo" '(meghanada-optimize-import :which-key "optimize")
 "li" '(meghanada-import-all :which-key "import"))

;;; java.el ends here
