;;; Markdown-Tools -- Summary:
;;; Commentary:
;;; Markdown configuration for Emacs
;;; generated by Zach Maas

;; This file contains config for all different markdown modes,
;; orgmode excepted
;;; Code:

(use-package markdown-mode
  :ensure t
  :commands (markdown-mode gfm-mode)
	:init
	(add-hook 'markdown-mode-hook #'whitespace-mode)
  :mode (("README\\.md\\'" . gfm-mode)
				 ("github\\.com.*\\.txt\\'" . gfm-mode)
         ("\\.md\\'" . markdown-mode)
         ("\\.markdown\\'" . markdown-mode))
  :init (setq markdown-command "multimarkdown"))

(use-package yaml-mode
	:ensure t)

(use-package toml-mode
	:ensure t)

;; FIXME
(general-define-key
 :states '(normal visual insert emacs)
 :prefix "SPC"
 :non-normal-prefix "M-SPC"
 "l" '(:ignore t :which-key "layer"))

;;; zm-org-tools.el ends here
