;;; Python-Tools -- Summary:
;;; Commentary:
;;; configuration of python editing packages for Emacs
;;; generated by Zach Maas

;;; Code:

;; Python Development Setup
;; IN PROGRESS - anaconda is good so far, some lag that needs to be figured out
(use-package anaconda-mode
	:ensure t
	:init
	(use-package virtualenvwrapper
		:ensure t
		:config
		(venv-initialize-interactive-shells)
		(venv-initialize-eshell))
	:config
	(add-hook 'python-mode-hook #'anaconda-mode))

(use-package company-anaconda
	:ensure t
	:config
	(setq python-shell-interpreter "ipython"
				python-shell-interpreter-args "--simple-prompt"
				python-shell-completion-native-disabled-interpreters "ipython")
	(eval-after-load "company"
		'(add-to-list 'company-backends 'company-anaconda))													
	(add-hook 'python-mode-hook 'anaconda-mode)																		
	(add-hook 'python-mode-hook																										
						(lambda ()																																
							(set (make-local-variable 'company-backends)											
									 '((company-anaconda company-dabbrev-code company-yasnippet))))))

;; New special symbols
(add-hook
 'python-mode-hook
 (lambda ()
   (mapc (lambda (pair) (push pair prettify-symbols-alist))
         '(;; Syntax
           ("def" .      #x2131)
           ("not" .      #x2757)
           ("in" .       #x2208)
           ("not in" .   #x2209)
           ("return" .   #x27fc)
           ("yield" .    #x27fb)
           ("for" .      #x2200)
           ;; Base Types
           ("int" .      #x2124)
           ("float" .    #x211d)
           ("str" .      #x1d54a)
           ("True" .     #x1d54b)
           ("False" .    #x1d53d)
           ;; Mypy
           ("Dict" .     #x1d507)
           ("List" .     #x2112)
           ("Tuple" .    #x2a02)
           ("Set" .      #x2126)
           ("Iterable" . #x1d50a)
           ("Any" .      #x2754)
           ("Union" .    #x22c3)))))

;;; zm-python-tools.el ends here
