;;; Python-Tools -- Summary:
;;; Commentary:
;;; configuration of python editing packages for Emacs
;;; generated by Zach Maas

;;; Code:

;; Python Development Setup
;; IN PROGRESS - anaconda is good so far, some lag that needs to be figured out
(use-package anaconda-mode
	:ensure t
	:init
	(use-package virtualenvwrapper
		:ensure t
		:config
		(venv-initialize-interactive-shells)
		(venv-initialize-eshell))
	:config
	(add-hook 'python-mode-hook #'anaconda-mode))

(use-package company-anaconda
	:ensure t
	:config
	(setq python-shell-interpreter "python3"
				python-shell-interpreter-args "")
  (when (executable-find "ipython")
    (setq python-shell-interpreter "ipython"
          python-shell-interpreter-args "-i --simple-prompt --no-color-info"
          python-shell-prompt-regexp "In \\[[0-9]+\\]: "
          python-shell-prompt-block-regexp "\\.\\.\\.\\.: "
          python-shell-prompt-output-regexp "Out\\[[0-9]+\\]: "
          python-shell-completion-setup-code
          "from IPython.core.completerlib import module_completion"
          python-shell-completion-string-code
          "';'.join(get_ipython().Completer.all_completions('''%s'''))\n"))

	(eval-after-load "company"
		'(add-to-list 'company-backends 'company-anaconda))													
	(add-hook 'python-mode-hook 'anaconda-mode)
	(add-hook 'anaconda-mode-hook #'anaconda-eldoc-mode)
	(add-hook 'python-mode-hook																										
						(lambda ()																																
							(set (make-local-variable 'company-backends)											
									 '((company-anaconda company-dabbrev-code company-yasnippet))))))

;; EIN - Emacs Ipython Notebooks
(use-package ein
	:ensure t)

;;; zm-python-tools.el ends here
