;;; R-Tools -- Summary:
;;; Commentary:
;;; R language configuration for Emacs
;;; generated by Zach Maas

;;; Code:

;; Base setup for using R
(use-package ess
	:ensure t)

(use-package polymode
	:ensure t
	:config
	(add-to-list 'auto-mode-alist '("\\.Rmd" . poly-markdown+r-mode)))

(general-define-key
 :states '(normal visual insert emacs)
 :keymaps 'ess-mode-map
 :prefix "SPC"
 :non-normal-prefix "M-SPC"
 "l" '(:ignore t :which-key "layer")
 "ll" '(ess-eval-region-or-function-or-paragraph :which-key "eval region")
 "le" '(ess-eval-buffer :which-key "eval buffer")
 "lR" '(R :which-key "R"))

;;; r.el ends here
