;;; R-Tools -- Summary:
;;; Commentary:
;;; R language configuration for Emacs
;;; generated by Zach Maas

;;; Code:

;; Base setup for using R
(use-package ess
	:straight t
	:config
	(use-package ess-view
		:straight t
		:config)
	;; Initialize R Server Protocol
	(lsp-register-client
	 (make-lsp-client :new-connection
										(lsp-stdio-connection '("R" "--slave" "-e" "languageserver::run()"))
										:major-modes '(ess-r-mode inferior-ess-r-mode)
										:server-id 'lsp-R)))
	(use-package polymode
		:straight t
		:config
		(add-to-list 'auto-mode-alist '("\\.Rmd" . poly-markdown+r-mode)))

;; (use-package matlab-mode
;; 	:straight t
;; 	:config
;; 	(add-to-list
;; 	 'auto-mode-alist
;; 	 '("\\.m$" . matlab-mode))
;; 	(setq matlab-indent-function t)
;; 	(setq matlab-shell-command "matlab")
;; 	(add-to-list 'company-backends 'company-matlab-shell))

(general-define-key
 :states '(normal visual insert emacs)
 :keymaps 'ess-mode-map
 :prefix "SPC"
 :non-normal-prefix "M-SPC"
 "l" '(:ignore t :which-key "layer")
 "ll" '(ess-eval-region-or-function-or-paragraph :which-key "eval region")
 "le" '(ess-eval-buffer :which-key "eval buffer")
 "lR" '(R :which-key "R"))

;;; r.el ends here
