;;; web.el -- Summary:
;;; Commentary:
;;; HTML and other configuration for Emacs
;;; generated by Zach Maas

;;; Code:

(use-package web-mode
	:ensure t)

(use-package emmet-mode
	:ensure t
	:config
	(add-hook 'html-mode-hook #'emmet-mode))

(use-package company-web
	:ensure t)

;;;	web.el ends here
