;;; Emacs-games -- Summary:
;;; Commentary:
;; configuration of circe for Emacs
;;; generated by Zach Maas

;;; Code:

(use-package typit
	:straight t)

(use-package fireplace
	:straight t)

;; games.el ends here
