;;; Emacs-IRC -- Summary:
;;; Commentary:
;; configuration of circe for Emacs
;;; generated by Zach Maas

;;; Code:

(use-package circe
	:straight t
	:config
	(enable-circe-color-nicks)
	(enable-circe-display-images)
	(circe-lagmon-mode)
	(setq lui-track-bar-behavior 'before-switch-to-buffer)
	(enable-lui-track-bar)
	(setq circe-reduce-lurker-spam t
				circe-format-server-topic "*** Topic change by {userhost}: {topic-diff}"
				circe-format-say "{nick:-16s} {body}"
				lui-flyspell-p t
				lui-flyspell-alist '((".*" "american"))
				lui-time-stamp-position 'right-margin
				lui-fill-type nil))

(use-package circe-notifications
	:straight t
	:config
	(eval-after-load "circe-notifications"
		'(setq circe-notifications-watch-strings
					 '())) ;; Nicks go here
	(add-hook 'circe-server-connected-hook 'enable-circe-notifications))

;; Custom auth functions
(defun ono-fetch-irc-password (&rest params)
  (require 'auth-source)
  (let ((match (car (apply 'auth-source-search params))))
    (if match
        (let ((secret (plist-get match :secret)))
          (if (functionp secret)
              (funcall secret)
            secret))
      (error "Password not found for %S" params))))

;; File with personal authentication info
(load-file "~/.emacs.d/apps/irc-private.el")

;; Allow circe to seamlessly adapt to window size changes
(add-hook 'lui-mode-hook 'ono-lui-setup)
(defun ono-lui-setup ()
  (setq
   fringes-outside-margins t
   right-margin-width 5
   word-wrap t
   wrap-prefix "    "))
